/**
 * Design reminder — Corporate Modern Mobile Operations:
 * RTL office settings, editable 70/30 distribution, explicit note-based exceptions, Cairo typography.
 */
import { type FormEvent, useState } from "react";
import { Building2, MapPin, Percent, Phone, Plus, Save, SlidersHorizontal, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { MorePageLayout } from "@/components/MorePageLayout";

type DistributionException = { id: string; keyword: string; captainShare: string; officeShare: string };
const createException = (): DistributionException => ({ id: crypto.randomUUID(), keyword: "", captainShare: "", officeShare: "" });

export default function OfficeSettings() {
  const [office, setOffice] = useState({ name: "دليفري طرطوس", phone: "0933000000", address: "طرطوس — مركز المدينة" });
  const [defaultSplit, setDefaultSplit] = useState({ captainShare: "70", officeShare: "30" });
  const [exceptions, setExceptions] = useState<DistributionException[]>([{ id: "exception-1", keyword: "طلب سريع", captainShare: "75", officeShare: "25" }]);
  const field = "mt-1.5 h-11 w-full rounded-xl border border-[#c9d9e7] bg-white px-3 text-sm focus:border-[#0060B8] focus:outline-none focus:ring-2 focus:ring-[#0060B8]/15";
  const updateException = (id: string, fieldName: keyof Omit<DistributionException, "id">, value: string) => setExceptions((current) => current.map((item) => item.id === id ? { ...item, [fieldName]: value } : item));
  const validSplit = (captainShare: string, officeShare: string) => Number(captainShare) + Number(officeShare) === 100 && Number(captainShare) >= 0 && Number(officeShare) >= 0;
  const save = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!validSplit(defaultSplit.captainShare, defaultSplit.officeShare)) return toast.error("يجب أن يكون مجموع نسب التوزيع الأساسية 100%.");
    const invalidException = exceptions.find((item) => !item.keyword.trim() || !validSplit(item.captainShare, item.officeShare));
    if (invalidException) return toast.error("أكمل نص الملاحظة ونسب التوزيع لكل استثناء، ويجب أن يكون مجموعهما 100%.");
    toast.success("تم حفظ نسب التوزيع والاستثناءات ضمن الواجهة.");
  };
  return <MorePageLayout title="إعدادات المكتب" subtitle="" Icon={SlidersHorizontal}>
    <section className="rounded-2xl border border-[#d3e3f0] bg-white p-4 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf4ff] text-[#0060B8]"><Building2 size={23} /></span><div><h2 className="text-[18px] font-bold">بيانات المكتب</h2><p className="mt-1 text-xs leading-5 text-[#58616b]">البيانات الأساسية التي تظهر ضمن تقارير وتشغيل المكتب.</p></div></div></section>
    <form onSubmit={save} className="mt-5 space-y-4"><section className="rounded-2xl border border-[#dbe7f2] bg-white p-4 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><label className="block text-xs font-bold text-[#4f5d6b]"><span className="flex items-center gap-1.5"><Building2 size={15} />اسم المكتب</span><input value={office.name} onChange={(event) => setOffice({ ...office, name: event.target.value })} className={field} /></label><label className="mt-3 block text-xs font-bold text-[#4f5d6b]"><span className="flex items-center gap-1.5"><Phone size={15} />رقم المكتب</span><input value={office.phone} onChange={(event) => setOffice({ ...office, phone: event.target.value })} inputMode="tel" className={field} /></label><label className="mt-3 block text-xs font-bold text-[#4f5d6b]"><span className="flex items-center gap-1.5"><MapPin size={15} />العنوان</span><input value={office.address} onChange={(event) => setOffice({ ...office, address: event.target.value })} className={field} /></label></section>
      <section className="rounded-2xl border border-[#dbe7f2] bg-white p-4 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><div className="flex items-center gap-2 text-sm font-bold"><Percent size={18} className="text-[#0060B8]" />نسب التوزيع الأساسية</div><p className="mt-1 text-[11px] leading-5 text-[#66727e]">هذه النسب تطبّق تلقائياً على الطلب عندما لا يطابق استثناءً خاصاً.</p><div className="mt-3 grid grid-cols-2 gap-3"><label className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700">حصة الكابتن<input value={defaultSplit.captainShare} onChange={(event) => setDefaultSplit({ ...defaultSplit, captainShare: event.target.value })} inputMode="decimal" className="mt-2 h-10 w-full rounded-lg border border-emerald-200 bg-white px-2 text-center text-xl font-bold text-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500/15" /><span className="mt-1 block text-center">%</span></label><label className="rounded-xl bg-blue-50 p-3 text-xs text-[#0060B8]">حصة المكتب<input value={defaultSplit.officeShare} onChange={(event) => setDefaultSplit({ ...defaultSplit, officeShare: event.target.value })} inputMode="decimal" className="mt-2 h-10 w-full rounded-lg border border-blue-200 bg-white px-2 text-center text-xl font-bold text-[#0060B8] focus:outline-none focus:ring-2 focus:ring-[#0060B8]/15" /><span className="mt-1 block text-center">%</span></label></div><p className={`mt-3 text-center text-[11px] font-bold ${validSplit(defaultSplit.captainShare, defaultSplit.officeShare) ? "text-emerald-700" : "text-[#ba1a1a]"}`}>المجموع: {Number(defaultSplit.captainShare || 0) + Number(defaultSplit.officeShare || 0)}%</p></section>
      <section className="rounded-2xl border border-amber-200 bg-[#fffdf8] p-4 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><div className="flex items-start gap-2"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-700"><SlidersHorizontal size={18} /></span><div><h2 className="text-sm font-bold text-[#5f471b]">استثناءات التوزيع</h2><p className="mt-1 text-[11px] leading-5 text-[#806636]">اكتب كلمة أو عبارة. عند وجودها في ملاحظات المصدر ضمن الطلب، تطبق النسبة المقابلة لها بدلاً من النسبة الأساسية.</p></div></div><div className="mt-3 space-y-3">{exceptions.map((item, index) => <div key={item.id} className="rounded-xl border border-amber-200 bg-white p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-bold text-amber-800">استثناء {index + 1}</span><button type="button" onClick={() => setExceptions((current) => current.filter((exception) => exception.id !== item.id))} className="grid h-7 w-7 place-items-center rounded-lg text-[#ba1a1a] hover:bg-red-50" aria-label="حذف الاستثناء"><Trash2 size={16} /></button></div><label className="block text-[11px] font-bold text-[#755a29]">النص المطابق في ملاحظات المصدر<input value={item.keyword} onChange={(event) => updateException(item.id, "keyword", event.target.value)} placeholder="مثال: طلب سريع" className="mt-1 h-10 w-full rounded-lg border border-amber-200 bg-[#fffdf8] px-3 text-sm focus:border-amber-500 focus:outline-none" /></label><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-[11px] font-bold text-emerald-700">الكابتن %<input value={item.captainShare} onChange={(event) => updateException(item.id, "captainShare", event.target.value)} inputMode="decimal" className="mt-1 h-9 w-full rounded-lg border border-emerald-200 px-2 text-center text-sm" /></label><label className="text-[11px] font-bold text-[#0060B8]">المكتب %<input value={item.officeShare} onChange={(event) => updateException(item.id, "officeShare", event.target.value)} inputMode="decimal" className="mt-1 h-9 w-full rounded-lg border border-blue-200 px-2 text-center text-sm" /></label></div><p className={`mt-2 text-[10px] font-bold ${validSplit(item.captainShare, item.officeShare) ? "text-emerald-700" : "text-[#ba1a1a]"}`}>المجموع: {Number(item.captainShare || 0) + Number(item.officeShare || 0)}%</p></div>)}</div><button type="button" onClick={() => setExceptions((current) => [...current, createException()])} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-amber-300 bg-amber-50 text-xs font-bold text-amber-800 active:scale-[0.98]"><Plus size={17} />إضافة استثناء توزيع</button></section>
      <button type="submit" className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#0060B8] text-sm font-bold text-white shadow-[0_4px_12px_rgba(0,96,184,0.2)] active:scale-[0.98]"><Save size={18} />حفظ الإعدادات</button></form>
  </MorePageLayout>;
}
