/**
 * Design reminder — Corporate Modern Mobile Operations:
 * RTL report composition, #0060B8 summary hierarchy, numeric operational cards, Cairo typography.
 */
import { useMemo, useState } from "react";
import { BarChart3, Building2, ClipboardList, TrendingUp, Truck } from "lucide-react";
import { MorePageLayout } from "@/components/MorePageLayout";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { captainProfiles, filterWageOrders, formatMoney, monthOptions, wageOrders } from "@/lib/wage-data";

export default function Reports() {
  const [month, setMonth] = useState(monthOptions[0].key);
  const orders = useMemo(() => filterWageOrders(wageOrders, "monthly", month), [month]);
  const totals = useMemo(() => orders.reduce((sum, order) => ({ gross: sum.gross + order.gross, captainDue: sum.captainDue + order.gross * 0.7, office: sum.office + order.gross * 0.3 }), { gross: 0, captainDue: 0, office: 0 }), [orders]);
  const daily = useMemo(() => Array.from(new Set(orders.map((order) => order.dayKey))).map((dayKey) => ({ dayKey, orders: orders.filter((order) => order.dayKey === dayKey) })).map((group) => ({ ...group, gross: group.orders.reduce((sum, order) => sum + order.gross, 0) })), [orders]);
  const captainTotals = useMemo(() => captainProfiles.map((captain) => ({ ...captain, gross: orders.filter((order) => order.captainId === captain.id).reduce((sum, order) => sum + order.gross, 0) })).filter((captain) => captain.gross > 0), [orders]);
  const monthLabel = monthOptions.find((option) => option.key === month)?.label;
  return <MorePageLayout title="التقارير" subtitle="" Icon={BarChart3}>
    <section className="rounded-2xl border border-[#d3e3f0] bg-white p-4 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><div className="flex items-start justify-between gap-3"><div><h2 className="text-[18px] font-bold">تقرير المكتب</h2><p className="mt-1 text-xs leading-5 text-[#58616b]">ملخص الطلبات والأجور ضمن الشهر المحدد.</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf4ff] text-[#0060B8]"><TrendingUp size={23} /></span></div><Select value={month} onValueChange={setMonth}><SelectTrigger className="mt-4 h-10 rounded-xl border-[#c9d9e7] bg-[#fbfdff] text-xs"><SelectValue /></SelectTrigger><SelectContent dir="rtl">{monthOptions.map((option) => <SelectItem key={option.key} value={option.key}>{option.label}</SelectItem>)}</SelectContent></Select></section>
    <section className="mt-4 rounded-2xl bg-[#0060B8] p-4 text-white shadow-[0_6px_16px_rgba(0,96,184,0.2)]"><span className="text-xs text-[#dceaff]">إجمالي أجور {monthLabel}</span><strong className="mt-1 block text-[25px]">{formatMoney(totals.gross)}</strong><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/12 p-2.5"><span className="block text-[10px] text-[#dceaff]">الكباتن 70%</span><strong className="mt-1 block text-sm">{formatMoney(totals.captainDue)}</strong></div><div className="rounded-xl bg-white/12 p-2.5"><span className="block text-[10px] text-[#dceaff]">المكتب 30%</span><strong className="mt-1 block text-sm">{formatMoney(totals.office)}</strong></div></div></section>
    <section className="mt-5 grid grid-cols-2 gap-3"><article className="rounded-2xl border border-[#dbe7f2] bg-white p-3.5 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><ClipboardList className="text-[#0060B8]" size={20} /><p className="mt-3 text-xs font-bold text-[#58616b]">طلبات الشهر</p><strong className="mt-1 text-xl">{orders.length}</strong></article><article className="rounded-2xl border border-[#dbe7f2] bg-white p-3.5 shadow-[0_2px_8px_rgba(0,72,141,0.05)]"><Building2 className="text-emerald-600" size={20} /><p className="mt-3 text-xs font-bold text-[#58616b]">صافي المكتب</p><strong className="mt-1 text-lg text-emerald-700">{formatMoney(totals.office)}</strong></article></section>
    <section className="mt-6"><h2 className="mb-3 text-base font-bold">الحصيلة اليومية</h2><div className="space-y-2">{daily.map((group) => <article key={group.dayKey} className="flex items-center justify-between rounded-2xl border border-[#dbe7f2] bg-white px-3.5 py-3 shadow-[0_2px_8px_rgba(0,72,141,0.04)]"><div><strong className="text-sm">{group.dayKey === "2026-08-19" ? "الثلاثاء 19 آب" : group.dayKey === "2026-08-18" ? "الاثنين 18 آب" : group.dayKey === "2026-07-28" ? "الثلاثاء 28 تموز" : "الاثنين 27 تموز"}</strong><span className="mt-1 block text-[11px] text-[#66727e]">{group.orders.length} طلبات</span></div><strong className="text-sm text-[#0060B8]">{formatMoney(group.gross)}</strong></article>)}</div></section>
    <section className="mt-6"><h2 className="mb-3 text-base font-bold">أجور الكباتن</h2><div className="space-y-2">{captainTotals.map((captain) => <article key={captain.id} className="flex items-center justify-between rounded-2xl border border-[#dbe7f2] bg-white px-3.5 py-3 shadow-[0_2px_8px_rgba(0,72,141,0.04)]"><span className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e7edf2] text-xs font-bold text-[#52606d]">{captain.initial}</span><span><strong className="block text-sm">{captain.name}</strong><span className="text-[10px] text-[#66727e]">حصة الكابتن 70%</span></span></span><span className="inline-flex items-center gap-1 text-sm font-bold text-emerald-700"><Truck size={15} />{formatMoney(captain.gross * 0.7)}</span></article>)}</div></section>
  </MorePageLayout>;
}
