import { useState } from 'react';
import { Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, Stack } from 'expo-router';

import { deliverySupabase } from '@/data/supabase/supabaseContract';
import { useAuthenticatedRedirect } from '@/features/auth/useAuthenticatedRedirect';

const logo = require('../../assets/images/delivery-tartous-office-logo.jpg');
const validEmail = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());

export default function ActivateAccountScreen() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useAuthenticatedRedirect();
  async function handleActivate() { const normalized = email.trim().toLowerCase(); if (!normalized || !password || !confirmation) { setError('أكمل جميع الحقول لتفعيل الحساب.'); return; } if (!validEmail(normalized)) { setError('أدخل بريداً إلكترونياً صحيحاً.'); return; } if (password.length < 12) { setError('يجب أن تتكون كلمة المرور من 12 حرفاً على الأقل.'); return; } if (password !== confirmation) { setError('تأكيد كلمة المرور غير مطابق.'); return; } if (loading) return; setLoading(true); setError(null); try { await deliverySupabase.auth.activatePendingAccount({ email: normalized, password, passwordConfirmation: confirmation }); await deliverySupabase.auth.signInWithPassword(normalized, password); } catch (cause) { const message = cause instanceof Error ? cause.message : ''; setError(/network|fetch|failed to fetch/i.test(message) ? 'تعذر الاتصال بالخادم. تحقق من الإنترنت ثم حاول مرة أخرى.' : 'تعذر تفعيل الحساب. تحقق من البيانات وتواصل مع الإدارة.'); } finally { setLoading(false); } }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><Stack.Screen options={{ headerShown: false }} /><View pointerEvents="none" style={styles.topCircle} /><View pointerEvents="none" style={styles.bottomCircle} /><View style={styles.card}><View style={styles.brand}><View style={styles.logoFrame}><Image source={logo} resizeMode="contain" style={styles.logo} /></View><Text style={styles.brandName}>دليفري طرطوس</Text><Text style={styles.title}>تفعيل حساب جديد</Text><Text style={styles.subtitle}>أدخل البريد الإلكتروني وكلمة مرور لحسابك</Text></View><View style={styles.form}><Field label="البريد الإلكتروني" icon="@" value={email} onChangeText={setEmail} placeholder="example.com@" keyboardType="email-address" editable={!loading} /><Field label="كلمة المرور" icon="⌑" value={password} onChangeText={setPassword} placeholder="••••••••" secureTextEntry editable={!loading} /><Field label="تأكيد كلمة المرور" icon="↻" value={confirmation} onChangeText={setConfirmation} placeholder="••••••••" secureTextEntry editable={!loading} />{error ? <View style={styles.errorBox}><Text style={styles.errorText}>{error}</Text></View> : null}<Pressable disabled={loading} onPress={() => void handleActivate()} style={[styles.activateButton, loading && styles.disabled]}><Text style={styles.activateButtonText}>{loading ? 'جارٍ تفعيل الحساب...' : 'تفعيل الحساب'}</Text></Pressable><Pressable disabled={loading} onPress={() => router.replace('/login')} style={styles.loginLink}><Text style={styles.loginLinkText}>العودة إلى تسجيل الدخول</Text></Pressable><Text style={styles.note}>لا يمكن تفعيل الحساب إلا بالبريد الإلكتروني المضاف مسبقاً.</Text></View></View></KeyboardAvoidingView>;
}
function Field({ label, icon, value, onChangeText, placeholder, editable, secureTextEntry = false, keyboardType = 'default' }: { label: string; icon: string; value: string; onChangeText: (value: string) => void; placeholder: string; editable: boolean; secureTextEntry?: boolean; keyboardType?: 'default' | 'email-address' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.inputShell}><Text style={styles.icon}>{icon}</Text><TextInput autoCapitalize="none" editable={editable} keyboardType={keyboardType} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#9BA8B1" secureTextEntry={secureTextEntry} style={styles.input} textAlign="right" value={value} /></View></View>; }
const styles = StyleSheet.create({ screen: { alignItems: 'center', backgroundColor: '#DCEEFE', flex: 1, justifyContent: 'center', overflow: 'hidden', padding: 18 }, topCircle: { borderColor: 'rgba(255,255,255,0.42)', borderRadius: 160, borderWidth: 24, height: 320, position: 'absolute', right: -118, top: -112, width: 320 }, bottomCircle: { borderColor: 'rgba(0,96,184,0.10)', borderRadius: 180, borderWidth: 32, bottom: -150, height: 360, left: -148, position: 'absolute', width: 360 }, card: { backgroundColor: 'rgba(255,255,255,0.84)', borderColor: 'rgba(255,255,255,0.88)', borderRadius: 32, borderWidth: 1, maxWidth: 410, padding: 22, shadowColor: '#0059A0', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.18, shadowRadius: 30, width: '100%' }, brand: { alignItems: 'center' }, logoFrame: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: 'rgba(255,255,255,0.9)', borderRadius: 20, borderWidth: 1, height: 78, justifyContent: 'center', overflow: 'hidden', padding: 5, shadowColor: '#0060B8', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.13, shadowRadius: 12, width: 78 }, logo: { height: '100%', width: '100%' }, brandName: { color: '#075BA6', fontSize: 21, fontWeight: '800', marginTop: 10 }, title: { color: '#1C2934', fontSize: 19, fontWeight: '800', marginTop: 12 }, subtitle: { color: '#62717E', fontSize: 12, marginTop: 5, textAlign: 'center' }, form: { gap: 10, marginTop: 20 }, field: { gap: 5 }, label: { color: '#475663', fontSize: 12, fontWeight: '800', textAlign: 'right' }, inputShell: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#AEBBC5', borderRadius: 12, borderWidth: 1, flexDirection: 'row-reverse', height: 52 }, icon: { color: '#60707D', fontSize: 18, paddingHorizontal: 13 }, input: { color: '#1C2934', flex: 1, fontSize: 15, height: '100%', paddingLeft: 10 }, errorBox: { backgroundColor: '#FEF2F2', borderColor: '#FECACA', borderRadius: 10, borderWidth: 1, padding: 10 }, errorText: { color: '#B91C1C', fontSize: 12, fontWeight: '700', textAlign: 'right' }, activateButton: { alignItems: 'center', backgroundColor: '#0068C6', borderRadius: 12, height: 54, justifyContent: 'center', marginTop: 3, shadowColor: '#0060B8', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.23, shadowRadius: 14 }, activateButtonText: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' }, loginLink: { alignItems: 'center', minHeight: 38, paddingTop: 8 }, loginLinkText: { color: '#0563B4', fontSize: 14, fontWeight: '800' }, note: { backgroundColor: 'rgba(255,255,255,0.60)', borderRadius: 10, color: '#697986', fontSize: 10, lineHeight: 16, padding: 10, textAlign: 'center' }, disabled: { opacity: 0.65 } });
