import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { deliveryColors, deliveryRadius, deliveryShadows, deliverySpacing } from '@/constants/deliveryTheme';

type InfoSection = { title: string; body: string };

export function NativeInfoPanel({ title, subtitle, sections, onClose }: { title: string; subtitle: string; sections: InfoSection[]; onClose: () => void }) {
  return <View style={styles.root}><View style={styles.header}><Pressable onPress={onClose} style={styles.back}><Text style={styles.backText}>رجوع</Text></Pressable><View><Text style={styles.headerTitle}>{title}</Text><Text style={styles.headerSubtitle}>{subtitle}</Text></View></View><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>{sections.map((section) => <View key={section.title} style={[styles.card, deliveryShadows.sm]}><Text style={styles.title}>{section.title}</Text><Text style={styles.body}>{section.body}</Text></View>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: deliveryColors.background }, header: { alignItems: 'center', backgroundColor: deliveryColors.primary, flexDirection: 'row-reverse', justifyContent: 'space-between', minHeight: 74, paddingHorizontal: deliverySpacing.lg }, headerTitle: { color: deliveryColors.surface, fontSize: 18, fontWeight: '800', textAlign: 'right' }, headerSubtitle: { color: '#D7EEFF', fontSize: 11, marginTop: 3, textAlign: 'right' }, back: { borderColor: '#FFFFFF66', borderRadius: deliveryRadius.md, borderWidth: 1, paddingHorizontal: deliverySpacing.md, paddingVertical: deliverySpacing.sm }, backText: { color: deliveryColors.surface, fontSize: 13, fontWeight: '800' }, scroll: { gap: deliverySpacing.md, padding: deliverySpacing.lg, paddingBottom: deliverySpacing.xxxl }, card: { backgroundColor: deliveryColors.surface, borderRadius: deliveryRadius.lg, padding: deliverySpacing.lg }, title: { color: deliveryColors.text, fontSize: 16, fontWeight: '800', textAlign: 'right' }, body: { color: deliveryColors.muted, fontSize: 13, lineHeight: 21, marginTop: deliverySpacing.sm, textAlign: 'right' } });
